### ISSUE TITLE
Puedes poner una ejemplo como utilizarlo? 

### ISSUE THREAD

**Issue by PercyWoeds** [neohunter/NubeFact#2]

**Comment by neohunter** [comment]
Esta en la pagina inicial del repositorio

https://github.com/neohunter/NubeFact

**Comment by PercyWoeds** [comment]
Pero no funciona me dice  uninitialized constant Nubefact

**Comment by neohunter** [comment]
Cuando pillas ayuda reporta bien que es lo que has intentado y los errores que tienes.

Si te dice uninitialized constant Nubefact es que no se ha incluido la libreria.

 * Estas usando rails?
 * Lo tienes en tu Gemfile?
 * Agregaste el archivo en config/initializer/nubefact.rb?

Tu error dice: `uninitialized constant Nubefact`. El nombre de la clase es `NubeFact`, con la `F` mayuscula, te habras equivocado?

**Comment by PercyWoeds** [comment]
si estoy usando Rails
Lo tengo en mi Gemfile
Y lo agregue al config

Cuando lo ejecuto en modo desarrollo 
Me envia este error , me falta algo incluso ya ejecute el bundle install


/home/percy/kinzuko/config/initializers/nubefact.rb:2:in `<top (required)>': uninitialized constant NubeFact (NameError)
	from /home/percy/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'

**Comment by neohunter** [comment]
Ejecuta

$ gem list | grep Nube

Que te regresa?

**Comment by PercyWoeds** [comment]
percy@dell:~/kinzuko$ gem list $ | grep Nube
percy@dell:~/kinzuko$ 

No me lista nada

**Comment by neohunter** [comment]
Aparentemente agregaste un signo $ despues de `gem list`. el comando correcto es: `gem list | grep Nube`.

la salida del comando `gem list` debe incluir `NubeFact`, si no lo incluye es que la gema no esta instalada, quizas falta `bundle install` o quizas no estas cargando el gemset correcto.

Evidentemente el error que te da es porque no ha cargado la gema.

Con la informacion que brindas no puedo ser de mas ayuda por aqui, es un problema de tu setup y no un issue con la gema.

**Comment by PercyWoeds** [comment]
Using nubefact 0.0.14

si esta instalado,  esta versión me sale cuando hago gem list

Por eso decía si tenias algún ejemplo que funcione, pero esta gema en verdad funciona o la estas desarrollando aun

**Comment by neohunter** [comment]
Funciona, se desarrollo hace como 3 anios y ha facturado miles de cosas. El
ejemplo del Readme deberia servir.

Si te dice uninitialized constant  prueba agregarle al inicio de tu
initialize:

```
require 'nube_fact'
```

**Comment by neohunter** [comment]
Acabo de actualizar el Readme.md me di cuenta que no estaba la instruccion del require,

**Comment by PercyWoeds** [comment]
Ayer ya lo pude hacer funcionar copiando todo el lib en mi proyecto.
